#Euler Problem 2 - Even Fibonacci Numbers

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


n = 0:10 
x = n + 1
y = x + 1
F = x + y


 for n in range(10)
 if (F%2 == 0):
 print F

#attempt 2

x = 1
y = 2
temp = 0
total = 0

while temp <= 4000000
    temp = y
    if (temp%2 == 0)
    total += temp

print(total)