import numpy as np
import os
import sys
import mat73
from scipy.interpolate import make_interp_spline, BSpline
from scipy import io
from scipy.signal import savgol_filter
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter
import pandas as pd
import matplotlib.colors as colors
import matplotlib.cm
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import spsolve
from scipy.interpolate import RectBivariateSpline
# from colorspacious import cspace_converter

#####Import Ollie Tools
# dirPath = "C:/Coding"
# sys.path.insert(0, dirPath)
# import OllieTools as oj
# print(dirPath)


####Import Ollie Tools MAC
dirPath = "/Users/olliejackson/Coding"
sys.path.insert(0, dirPath)
import OllieTools as oj
print(dirPath)

##### Set plot style #####
plt.style.use(["science", "vibrant", "no-latex"])
cmap = plt.get_cmap("jet_r")


def get_velocity_vortex(strength, xv, yv, X, Y):
    """Returns the velocity field generated by a vortex.
    
    Arguments
    ---------
    strength -- strength of the vortex.
    xv, yv -- coordinates of the vortex.
    X, Y -- mesh grid.
    """
    u = + strength/(2*np.pi)*(Y-yv)/((X-xv)**2+(Y-yv)**2)
    v = - strength/(2*np.pi)*(X-xv)/((X-xv)**2+(Y-yv)**2)


    return u, v

def calculate_vorticity(u, v):
    """
    calculates vorticity of velocity field
     
    INPUT:
        u           : 3D Numpy tensor containing velocity data
        v           : 3D Numpy tensor containing velocity data

    OUTPUT:
        Vorticity   : 3D Numpy tensor containing velocity data
        vorticity_gauss : 3D Numpy tensor containing velocity data after a gausian filter

    """
    dv = np.gradient(v, axis = 1)
    du = np.gradient(u, axis = 0)
    vorticity = dv - du
    vorticity_gauss = gaussian_filter(vorticity, sigma = 0.7)
    return vorticity, vorticity_gauss

def sum_Vorticity(
    u, v, 
):
    vorticity, vorticity_gauss = calculate_vorticity(u, v)

    vortTemp = vorticity[:, :]
    sumVorticity = np.sum(abs(vorticity[:, :]))

    return sumVorticity

def vortex_velocity_field(K, x, y):
  r = np.sqrt(x**2 + y**2)
  u = -K * x / r**2
  v = -K * y / r**2
  return u, v

def vorticityPeakTracking(u, v, l = 0):
    vorticity, vort_gauss = calculate_vorticity(u, v)
    VortLocMax = np.zeros((vort_gauss.shape[0], 2)) #same length in time as vorticity field, 2 rows - 0 for y, 1 for x
    VortLocMin = np.zeros((vort_gauss.shape[0], 2)) #same length in time as vorticity field, 2 rows - 0 for y, 1 for x

    if l == 0:
        l = vort_gauss.shape[0]
    elif l > vort_gauss.shape[0]:
        l = vort_gauss.shape[0]
    
    for i in range(l):
        vortTemp = vort_gauss[i, :, :]
        VortLocMax[i,:] = np.argwhere(vortTemp == np.max(vortTemp))
        VortLocMin[i,:] = np.argwhere(vortTemp == np.min(vortTemp))
    
    return VortLocMax, VortLocMin

def find_vortex_center_Vorticity(u, v, guass = 3, range = 3):
    """
    Finds the center of a vortex in a 2D velocity field using the vorticity field and interpolating the maxima location using a 2nd order bilinear polynomial fit at a resolution of 100* the original.

    Args:
        u: The x-component of the velocity field.
        v: The y-component of the velocity field.

    Returns:
        The center of the vortex, as a tuple of (x, y) coordinates.
    """
    scale = 0.05
    dvdx = np.gradient(v, axis=1)
    dudy = np.gradient(u, axis=0)
    
    vorticity = (0.5 * (dvdx - dudy))
    vortSmooth = np.abs(gaussian_filter(vorticity, guass))

    MaxLoc = np.argwhere(vortSmooth == np.max(vortSmooth))[0]
    if MaxLoc[0] < 15 or MaxLoc[0] > u.shape[0] - 15 or MaxLoc[1] < 15 or MaxLoc[1] > u.shape[1] - 15:
        xNew, yNew = 0, 0
    else:
        Sect = vortSmooth[MaxLoc[0]-range:MaxLoc[0]+range+1, MaxLoc[1]-range:MaxLoc[1]+range+1]
        # ax2.contourf(Sect)
        SplineSect = RectBivariateSpline(np.arange(Sect.shape[-2]), np.arange(Sect.shape[-1]), Sect, kx = 2, ky = 2)
        SectDetailed = SplineSect(np.arange(0, Sect.shape[-2]-1, scale), np.arange(0, Sect.shape[-1]-1, scale), grid=True)
        # ax3.contourf(SectDetailed)
        yNew = MaxLoc[0]-range + np.argwhere(SectDetailed == np.max(SectDetailed))[0][0] * scale
        xNew = MaxLoc[1]-range + np.argwhere(SectDetailed == np.max(SectDetailed))[0][1] * scale

    return xNew, yNew, vorticity, vortSmooth

time = 10 # Number of time steps
Gamma = 1.0  # Circulation strength of the vortex
x0, y0 = 0, 0  # Vortex center coordinates
x0 = [-5, -3, -1, 0, 1, 3, 5, 5, 5, 5, 5]

# Grid parameters
x_min, x_max, y_min, y_max = -10, 10, -10, 10
num_points = 101
x = np.linspace(x_min, x_max, num_points)
y = np.linspace(y_min, y_max, num_points)
X, Y = np.meshgrid(x, y)
u = np.empty((time, num_points, num_points))
v = np.empty((time, num_points, num_points))


xlist = []
for i in range(time):
    # x0 = -5 + i
    # xlist.append(x0)
    # y0 = y_min + 2*i
    # Calculate velocity components due to the vortex
    # u[(i),:,:] =  (Gamma / (2 * np.pi)) * (Y - y0) / ((X - x0)**2 + (Y - y0)**2)
    # v[(i),:,:] = -(Gamma / (2 * np.pi)) * (X - x0) / ((X - x0)**2 + (Y - y0)**2)
    u[(i),:,:] =  (Gamma / (2 * np.pi)) * (Y - y0) / ((X - x0[i])**2 + (Y - y0)**2)
    v[(i),:,:] = -(Gamma / (2 * np.pi)) * (X - x0[i]) / ((X - x0[i])**2 + (Y - y0)**2)


if u.shape[1] % 2 != 0:
    u = np.nan_to_num(u)
    v = np.nan_to_num(v)
    # u[:,int((u.shape[1]/2)),int((u.shape[2]/2))] = 0
    # v[:,int((v.shape[1]/2)),int((v.shape[2]/2))] = 0


# Plot the streamlines
# plt.figure(figsize=(8, 6))
plt.streamplot(X, Y, u[9,:,:], v[9,:,:], density=2, linewidth=1, arrowsize=2, arrowstyle='->', color="b")

# Plot the vortex center
plt.plot(x0[9], y0, 'ro')  # Red dot for the vortex center

# Set plot limits and labels
plt.xlim(x_min, x_max)
plt.ylim(y_min, y_max)
plt.xlabel('X')
plt.ylabel('Y')
plt.title('2D Vortex Flow Field')
plt.grid(True)
# plt.show()

f3, ax3 = plt.subplots()
ax3.quiver(X, Y, u[7,:,:], v[7,:,:], pivot = "middle")
# plt.show()

vort, vortG = oj.calculate_vorticity(u, v)

f4, ax4 = plt.subplots()
ax4.imshow(vort[7,:,:])
# plt.show()

VortLocMax, VortLocMin = vorticityPeakTracking(u, v)

f4, axs = plt.subplots(2, 2, sharex=True, sharey=True)
axs[0,0].contourf(vort[0,:,:])
# axs[0,0].scatter(VortLocMin[0,0],VortLocMin[0,1])
axs[0,0].plot(VortLocMin[:,1])
axs[0,1].contourf(vort[3,:,:])
axs[0,1].scatter(VortLocMin[:,0],VortLocMin[:,1])
axs[1,0].contourf(vort[6,:,:])
axs[1,0].scatter(VortLocMin[6,0],VortLocMin[6,1])
axs[1,1].contourf(vort[9,:,:])
axs[1,1].scatter(VortLocMin[9,1],VortLocMin[9,0])
axs[0,0].set_title("vorticity frame 0")
axs[0,1].set_title("vorticity frame 3")
axs[1,0].set_title("vorticity frame 6")
axs[1,1].set_title("vorticity frame 9")
plt.legend()


f5, ax4 = plt.subplots()
ax4.plot(VortLocMin[:,0])
# plt.show()


# for i in range(time):
#     x0 = x_min + 2*i
#     y0 = y_min + 2*i
#     # Calculate velocity components due to the vortex
#     u[(i),:,:] = Y
#     v[(i),:,:] = 0


f3, ax3 = plt.subplots()
ax3.quiver(X, Y, u[9,:,:], v[9,:,:], pivot = "middle")


f4, ax4 = plt.subplots()
ax4.contourf(vort[4,:,:])
plt.show()


u_az = 0
oj.animate_cube_quiver(u, v, u_az, interval=11.1, cmap="bwr", save=0, output="15.mp4", Dir="C:/Users/u2088308/Videos", name="vid.mp4", fps=90, scale = 1, fsize = (19, 12))


#TRYING SAM'S CODE - xNew, yNew are x and y coords of vortex centre for a single frame, vorticity is vorticity, and smooth has been filtered.
xNew, yNew, vorticity, vortSmooth = find_vortex_center_Vorticity(u[7,:,:], v[7,:,:], guass = 3, range = 3)

print(xNew, yNew)

#creating a new 3d variable for vortex location
xMax = np.zeros((u.shape[0], 1))
yMax = np.zeros((u.shape[0], 1))
print(xMax.shape)

for i in range(time):
    xMax[i,:], yMax[i,:], vorticity, vortSmooth = find_vortex_center_Vorticity(u[i,:,:], v[i,:,:], guass = 3, range = 10)


print(xMax[7,:])
print(yMax[7,:])


f4, axs = plt.subplots(2, 2, sharex=True, sharey=True)
axs[0,0].contourf(vort[0,:,:])
axs[0,0].plot(xMax[0,0], yMax[0,0])
axs[0,1].contourf(vort[3,:,:])
axs[0,1].scatter(VortLocMin[:,0],VortLocMin[:,1])
axs[1,0].contourf(vort[6,:,:])
axs[1,0].scatter(VortLocMin[6,0],VortLocMin[6,1])
axs[1,1].contourf(vort[9,:,:])
axs[1,1].scatter(VortLocMin[9,1],VortLocMin[9,0])
axs[0,0].set_title("vorticity frame 0")
axs[0,1].set_title("vorticity frame 3")
axs[1,0].set_title("vorticity frame 6")
axs[1,1].set_title("vorticity frame 9")
plt.legend()

f1, ax1 = plt.subplots()
ax1.plot(xMax[:], label = "new method")#, yMax[:,0])
ax1.plot(VortLocMin[:,1], label = "old method")
ax1.plot(xlist[:], label = "x0")
plt.legend()




f2, ax2 = plt.subplots()
ax2.contourf(u[5,:,:])
plt.legend()
plt.show()