import numpy as np
import os
import sys
import mat73
from scipy.interpolate import make_interp_spline, BSpline
from scipy import io
from scipy.signal import savgol_filter
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter
import pandas as pd
import matplotlib.colors as colors
import matplotlib.cm
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import spsolve
# from colorspacious import cspace_converter

#####Import Ollie Tools
dirPath = "C:/Coding"
sys.path.insert(0, dirPath)
import OllieTools as oj
print(dirPath)


####Import Ollie Tools MAC
# dirPath = "/Users/olliejackson/Coding"
# sys.path.insert(0, dirPath)
# import OllieTools as oj
# print(dirPath)

##### Set plot style #####
plt.style.use(["science", "vibrant", "no-latex"])
cmap = plt.get_cmap("jet_r")


N = 51                                # Number of points in each direction
x_start, x_end = -10.0, 10.0          # x-direction boundaries
y_start, y_end = -10.0, 10.0          # y-direction boundaries
x = np.linspace(x_start, x_end, N)    # computes a 1D-array for x
y = np.linspace(y_start, y_end, N)    # computes a 1D-array for y
X, Y = np.meshgrid(x, y)              # generates a mesh grid

gamma = 1.0                      # strength of the vortex
x_vortex, y_vortex = 0.5, 0.5    # location of the vortex

def get_velocity_vortex(strength, xv, yv, X, Y):
    """Returns the velocity field generated by a vortex.
    
    Arguments
    ---------
    strength -- strength of the vortex.
    xv, yv -- coordinates of the vortex.
    X, Y -- mesh grid.
    """
    u = + strength/(2*np.pi)*(Y-yv)/((X-xv)**2+(Y-yv)**2)
    v = - strength/(2*np.pi)*(X-xv)/((X-xv)**2+(Y-yv)**2)
    # r = np.sqrt(X**2 + Y**2)
    # u = -strength * X / r**2
    # v = -strength * Y / r**2


    return u, v

def get_stream_function_vortex(strength, xv, yv, X, Y):
    """Returns the stream-function generated by a vortex.
    
    Arguments
    ---------
    strength -- strength of the vortex.
    xv, yv -- coordinates of the vortex.
    X, Y -- mesh grid.
    """
    psi = strength/(4*np.pi)*np.log((X-xv)**2+(Y-yv)**2)
    
    return psi

def calculate_vorticity(u, v):
    """
    calculates vorticity of velocity field
     
    INPUT:
        u           : 3D Numpy tensor containing velocity data
        v           : 3D Numpy tensor containing velocity data

    OUTPUT:
        Vorticity   : 3D Numpy tensor containing velocity data
        vorticity_gauss : 3D Numpy tensor containing velocity data after a gausian filter

    """
    dv = np.gradient(v, axis = 1)
    du = np.gradient(u, axis = 0)
    vorticity = dv - du
    vorticity_gauss = gaussian_filter(vorticity, sigma = 0.7)
    return vorticity, vorticity_gauss

def sum_Vorticity(
    u, v, 
):
    vorticity, vorticity_gauss = calculate_vorticity(u, v)

    vortTemp = vorticity[:, :]
    sumVorticity = np.sum(abs(vorticity[:, :]))

    return sumVorticity

def vortex_velocity_field(K, x, y):
  r = np.sqrt(x**2 + y**2)
  u = -K * x / r**2
  v = -K * y / r**2
  return u, v







Gamma = 1.0  # Circulation strength of the vortex
x0, y0 = 0, 0  # Vortex center coordinates

# Grid parameters
x_min, x_max, y_min, y_max = -10, 10, -10, 10
num_points = 101
x = np.linspace(x_min, x_max, num_points)
y = np.linspace(y_min, y_max, num_points)
X, Y = np.meshgrid(x, y)

# Calculate velocity components due to the vortex
u =  (Gamma / (2 * np.pi)) * (Y - y0) / ((X - x0)**2 + (Y - y0)**2)
v = -(Gamma / (2 * np.pi)) * (X - x0) / ((X - x0)**2 + (Y - y0)**2)

# Plot the streamlines
plt.figure(figsize=(8, 6))
plt.streamplot(X, Y, u, v, density=2, linewidth=1, arrowsize=2, arrowstyle='->', color="b")


# Plot the vortex center
plt.plot(x0, y0, 'ro')  # Red dot for the vortex center

# Set plot limits and labels
plt.xlim(x_min, x_max)
plt.ylim(y_min, y_max)
plt.xlabel('X')
plt.ylabel('Y')
plt.title('2D Vortex Flow Field')
plt.grid(True)
# plt.show()


if u.shape[0] % 2 != 0:
    u[int((u.shape[0]/2)),int((u.shape[1]/2))] = 0
    v[int((v.shape[0]/2)),int((v.shape[1]/2))] = 0

Vorticity, vorticity_gauss = calculate_vorticity(u, v)

# if u.shape[0] % 2 != 0:
#     Vorticity = np.nan_to_num(Vorticity)
#     Vorticity[int((Vorticity.shape[0]/2)),int((Vorticity.shape[1]/2))] = 0

# Vorticity= gaussian_filter(Vorticity, sigma = 1)

f2, ax2 = plt.subplots()
ax2.imshow(Vorticity, cmap = "bwr")
f2.colorbar(matplotlib.cm.ScalarMappable(cmap="bwr"), ax=ax2)


f3, ax3 = plt.subplots()
ax3.quiver(u, v, pivot = "middle")#, cmap = "bwr")
ax3.plot(((u.shape[0]-1)/2), ((u.shape[1]-1)/2), 'ro')
# f3.colorbar(matplotlib.cm.ScalarMappable(cmap="bwr"), ax=ax3)


fig, ax = plt.subplots(2, 2, sharex=True, sharey=True)
ax[0,0].plot(u[int(u.shape[0]/2),:], c = "b") # u deviation in x
ax[0,1].plot(u[:,int(u.shape[1]/2)], c = "b") # u deviation in y
# ax[0,1].axvline(x = (u.shape[0]-1)/2, linestyle = "--")
ax[1,0].plot(v[int(v.shape[0]/2),:], c = "b") # v deviation in x
# ax[1,0].axvline(x = (v.shape[0]-1)/2, linestyle = "--")
ax[1,1].plot(v[:,int(v.shape[1]/2)], c = "b") # v deviation in y
ax[0,0].set_title("u deviation in x")
ax[0,1].set_title("u deviation in y")
ax[1,0].set_title("v deviation in x")
ax[1,1].set_title("v deviation in y")
plt.legend()
plt.show()

sVorticity = sum_Vorticity(u, v)
print(sVorticity)























