import numpy as np
import os
import sys
import mat73
from scipy.interpolate import make_interp_spline, BSpline
from scipy import io
from scipy.signal import savgol_filter
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter
import pandas as pd
import matplotlib.colors as colors
import matplotlib.cm
# from colorspacious import cspace_converter

#####Import Ollie Tools
dirPath = "C:/Coding"
sys.path.insert(0, dirPath)
import OllieTools as oj
print(dirPath)


####Import Ollie Tools MAC
# dirPath = "/Users/olliejackson/Coding"
# sys.path.insert(0, dirPath)
# import OllieTools as oj
# print(dirPath)

##### Set plot style #####
plt.style.use(["science", "vibrant", "no-latex"])
cmap = plt.get_cmap("jet_r")


N = 50                                # Number of points in each direction
x_start, x_end = -10.0, 10.0            # x-direction boundaries
y_start, y_end = -10.0, 10.0            # y-direction boundaries
x = np.linspace(x_start, x_end, N)    # computes a 1D-array for x
y = np.linspace(y_start, y_end, N)    # computes a 1D-array for y
X, Y = np.meshgrid(x, y)              # generates a mesh grid

gamma = 1.0                      # strength of the vortex
x_vortex, y_vortex = 0.0, 0.0    # location of the vortex

def get_velocity_vortex(strength, xv, yv, X, Y):
    """Returns the velocity field generated by a vortex.
    
    Arguments
    ---------
    strength -- strength of the vortex.
    xv, yv -- coordinates of the vortex.
    X, Y -- mesh grid.
    """
    u = + strength/(2*np.pi)*(Y-yv)/((X-xv)**2+(Y-yv)**2)
    v = - strength/(2*np.pi)*(X-xv)/((X-xv)**2+(Y-yv)**2)
    
    return u, v

def get_stream_function_vortex(strength, xv, yv, X, Y):
    """Returns the stream-function generated by a vortex.
    
    Arguments
    ---------
    strength -- strength of the vortex.
    xv, yv -- coordinates of the vortex.
    X, Y -- mesh grid.
    """
    psi = strength/(4*np.pi)*np.log((X-xv)**2+(Y-yv)**2)
    
    return psi


def calculate_vorticity(u, v):
    """
    calculates vorticity of velocity field
     
    INPUT:
        u           : 3D Numpy tensor containing velocity data
        v           : 3D Numpy tensor containing velocity data

    OUTPUT:
        Vorticity   : 3D Numpy tensor containing velocity data
        vorticity_gauss : 3D Numpy tensor containing velocity data after a gausian filter

    """
    dv = np.gradient(v, axis = 1)
    du = np.gradient(u, axis = 0)
    vorticity = dv - du
    vorticity_gauss = gaussian_filter(vorticity, sigma = 0.7)
    return vorticity, vorticity_gauss

def sum_Vorticity(
    u, v, 
):
    vorticity, vorticity_gauss = calculate_vorticity(u, v)

    vortTemp = vorticity[:, :]
    sumVorticity = np.sum(abs(vorticity[:, :]))

    return sumVorticity

def vortex_velocity_field(K, x, y):
  r = np.sqrt(x**2 + y**2)
  u = -K * x / r**2
  v = -K * y / r**2
  return u, v

# Set the strength of the vortex
K = 1

# Calculate the velocity field at a point (1, 1)
x = 1
y = 1
u, v = vortex_velocity_field(K, x, y)
print("Velocity field at point (1, 1):")
print("u:", u)
print("v:", v)

# Calculate the velocity field at a point (0, 0)
x = 0
y = 0
u, v = vortex_velocity_field(K, x, y)
print("Velocity field at point (0, 0):")
print("u:", u)
print("v:", v)


# computes the velocity field on the mesh grid
u_vortex, v_vortex = get_velocity_vortex(gamma, x_vortex, y_vortex, X, Y)

# computes the stream-function on the mesh grid
psi_vortex = get_stream_function_vortex(gamma, x_vortex, y_vortex, X, Y)

# plots the streamlines
# %matplotlib inline

size = 10
plt.figure(figsize=(size, (y_end-y_start)/(x_end-x_start)*size))
plt.xlabel('x', fontsize=16)
plt.ylabel('y', fontsize=16)
plt.xlim(x_start, x_end)
plt.ylim(y_start, y_end)
plt.streamplot(X, Y, u_vortex, v_vortex, density=2, linewidth=1, arrowsize=1, arrowstyle='->', color='b')
plt.scatter(x_vortex, y_vortex, color='#CD2305', s=80, marker='o');

print(u_vortex.shape)
f1, ax1 = plt.subplots()
ax1.plot(u_vortex[:,25])


Vorticity, vorticity_gauss = calculate_vorticity(u_vortex, v_vortex)

f2, ax2 = plt.subplots()
ax2.contourf(vorticity_gauss, cmap = "bwr")
f2.colorbar(matplotlib.cm.ScalarMappable(cmap="bwr"), ax=ax2)


# f3, ax3 = plt.subplots()
# ax3.imshow(u_vortex, cmap = "bwr")
# f2.colorbar(matplotlib.cm.ScalarMappable(cmap="bwr"), ax=ax2)




print(v_vortex.shape[1])

fig, ax = plt.subplots(2, 2, sharex=True, sharey=True)
ax[0,0].plot(u_vortex[int(u_vortex.shape[0]/2),:], label = "u deviation in x") # u deviation in x
ax[0,1].plot(u_vortex[:,int(u_vortex.shape[1]/2)], label = "u deviation in y") # u deviation in y
ax[1,0].plot(v_vortex[int(v_vortex.shape[0]/2),:], label = "v deviation in x") # v deviation in x
ax[1,1].plot(v_vortex[:,int(v_vortex.shape[1]/2)], label = "v deviation in y") # v deviation in y
ax[0,0].set_title("u deviation in x")
ax[0,1].set_title("u deviation in y")
ax[1,0].set_title("v deviation in x")
ax[1,1].set_title("v deviation in y")
plt.legend()
plt.show()

sVorticity = sum_Vorticity(u_vortex, v_vortex)
print(sVorticity)